/* The following code was generated by JFlex 1.4.3 on 4/10/12 6:08 PM */

/*stl.flex*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/10/12 6:08 PM from the specification file
 * <tt>stl.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\37\2\40\1\41\22\0\1\36\1\20\1\33\2\0"+
    "\1\30\1\0\1\32\6\0\1\34\1\0\12\31\2\0\1\26\1\21"+
    "\1\27\2\0\1\7\1\23\1\22\1\12\1\3\1\2\1\35\1\16"+
    "\1\1\2\35\1\4\1\35\1\11\1\6\1\14\1\25\1\13\1\5"+
    "\1\10\1\17\1\24\1\15\3\35\4\0\1\35\1\0\1\7\1\23"+
    "\1\22\1\12\1\3\1\2\1\35\1\16\1\1\2\35\1\4\1\35"+
    "\1\11\1\6\1\14\1\25\1\13\1\5\1\10\1\17\1\24\1\15"+
    "\3\35\12\0\1\40\u1fa2\0\2\40\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\14\2\2\1\4\2\1\3\1\4\1\5"+
    "\1\6\2\1\1\7\1\10\6\2\1\11\5\2\1\12"+
    "\1\13\4\2\1\14\1\15\1\16\4\0\1\17\1\20"+
    "\4\2\1\21\1\22\1\2\1\23\6\2\2\0\3\24"+
    "\1\25\1\26\1\2\1\27\1\30\1\31\2\2\1\32"+
    "\1\2\1\33\1\2\1\0\3\24\1\34\1\35\1\2"+
    "\1\36\2\2\3\0\1\34\1\37\2\2\1\40\1\0"+
    "\1\41\1\2\1\40\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe"+
    "\0\u0220\0\u0242\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec\0\u030e"+
    "\0\u0330\0\u0352\0\u0374\0\u0176\0\u0396\0\u03b8\0\u03da\0\u03fc"+
    "\0\u041e\0\u0440\0\u0176\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea"+
    "\0\42\0\42\0\u050c\0\u052e\0\u0550\0\u0572\0\42\0\42"+
    "\0\42\0\u0594\0\u05b6\0\u05d8\0\u0352\0\42\0\u0176\0\u05fa"+
    "\0\u061c\0\u063e\0\u0660\0\u0176\0\u0176\0\u0682\0\u0176\0\u06a4"+
    "\0\u06c6\0\u06e8\0\u070a\0\u072c\0\u074e\0\u0770\0\u0792\0\42"+
    "\0\u0770\0\u07b4\0\u05b6\0\42\0\u07d6\0\u0176\0\u0176\0\u0176"+
    "\0\u07f8\0\u081a\0\u0176\0\u083c\0\u0176\0\u085e\0\u0880\0\u08a2"+
    "\0\u0792\0\u08c4\0\42\0\u0176\0\u08e6\0\u0176\0\u0908\0\u092a"+
    "\0\u094c\0\u08a2\0\u096e\0\u08a2\0\u0176\0\u0990\0\u09b2\0\u094c"+
    "\0\u09d4\0\u0176\0\u09f6\0\u09d4\0\u0176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\14\1\16\2\14\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\2\1\14\2\33\2\2\43\0"+
    "\1\14\1\34\6\14\1\35\6\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\3\14\1\36\2\14\1\37"+
    "\10\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\3\14\1\40\13\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\5\14\1\41\11\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\2\14\1\42\14\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\12\14\1\43"+
    "\4\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\10\14\1\44\6\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\12\14\1\45\4\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\5\14\1\46\11\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\17\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\2\14\1\47"+
    "\14\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\15\14\1\50\1\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\25\0\1\51\41\0\1\52\21\0\15\14\1\53"+
    "\1\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\5\14\1\54\11\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\5\14\1\55\11\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\16\14\1\56\2\0\4\14"+
    "\3\0\1\14\3\0\1\14\25\0\1\57\4\0\1\60"+
    "\34\0\1\61\50\0\1\62\42\0\1\30\2\0\1\63"+
    "\5\0\32\64\1\0\7\64\33\65\1\66\6\65\36\0"+
    "\2\33\3\0\7\14\1\67\7\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\5\14\1\70\11\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\3\14\1\71"+
    "\13\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\4\14\1\72\12\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\5\14\1\73\11\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\7\14\1\74\7\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\11\14\1\75"+
    "\5\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\16\14\1\76\2\0\4\14\3\0\1\14\3\0\1\14"+
    "\5\0\7\14\1\77\7\14\2\0\4\14\3\0\1\14"+
    "\3\0\1\14\5\0\7\14\1\100\7\14\2\0\4\14"+
    "\3\0\1\14\3\0\1\14\5\0\1\101\16\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\6\14\1\102"+
    "\10\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\5\14\1\103\11\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\1\104\16\14\2\0\4\14\3\0\1\14"+
    "\3\0\1\14\5\0\2\14\1\105\14\14\2\0\4\14"+
    "\3\0\1\14\3\0\1\14\4\0\30\106\1\107\6\106"+
    "\1\110\1\111\1\112\31\0\1\113\42\0\1\114\10\0"+
    "\6\14\1\115\10\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\4\14\1\76\12\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\2\14\1\116\14\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\13\14\1\117"+
    "\3\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\2\14\1\120\14\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\16\14\1\121\2\0\4\14\3\0\1\14"+
    "\3\0\1\14\5\0\3\14\1\122\13\14\2\0\4\14"+
    "\3\0\1\14\3\0\1\14\5\0\12\14\1\123\4\14"+
    "\2\0\4\14\3\0\1\14\3\0\1\14\5\0\3\14"+
    "\1\124\13\14\2\0\4\14\3\0\1\14\3\0\1\14"+
    "\5\0\11\14\1\125\5\14\2\0\4\14\3\0\1\14"+
    "\3\0\1\14\5\0\4\14\1\126\12\14\2\0\4\14"+
    "\3\0\1\14\3\0\1\14\4\0\37\106\1\110\1\111"+
    "\1\112\30\107\1\127\6\107\1\130\1\131\1\132\37\106"+
    "\1\133\1\111\1\112\1\0\7\14\1\134\7\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\5\0\12\14\1\135"+
    "\4\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\2\14\1\136\14\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\2\14\1\137\14\14\2\0\4\14\3\0"+
    "\1\14\3\0\1\14\5\0\7\14\1\140\7\14\2\0"+
    "\4\14\3\0\1\14\3\0\1\14\4\0\30\107\1\141"+
    "\6\107\1\130\1\131\1\132\30\142\1\143\11\142\30\107"+
    "\1\127\6\107\1\144\1\131\1\132\1\0\10\14\1\145"+
    "\6\14\2\0\4\14\3\0\1\14\3\0\1\14\5\0"+
    "\6\14\1\146\10\14\2\0\4\14\3\0\1\14\3\0"+
    "\1\14\5\0\1\147\16\14\2\0\4\14\3\0\1\14"+
    "\3\0\1\14\4\0\30\107\1\150\6\107\1\130\1\131"+
    "\1\132\30\142\1\151\11\142\1\0\10\14\1\152\6\14"+
    "\2\0\4\14\3\0\1\14\3\0\1\14\5\0\5\14"+
    "\1\153\11\14\2\0\4\14\3\0\1\14\3\0\1\14"+
    "\4\0\30\142\1\154\11\142\1\0\10\14\1\155\6\14"+
    "\2\0\4\14\3\0\1\14\3\0\1\14\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2584];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\46\1\2\11\4\1\3\11\4\0\1\11"+
    "\17\1\2\0\1\11\3\1\1\11\12\1\1\0\3\1"+
    "\1\11\5\1\3\0\5\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser)
  {
    this(r);
    this.yyparser = yyparser;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { System.out.println("lex: found and\n"); return (Parser.AND);
          }
        case 35: break;
        case 24: 
          { System.out.println("lex: found loop\n"); return (Parser.LOOP);
          }
        case 36: break;
        case 21: 
          { System.out.println("lex: found float_literal\n");
					yyparser.yylval = new ParserVal(Double.parseDouble(yytext())); 
					return (Parser.FLOATLITERAL);
          }
        case 37: break;
        case 16: 
          { System.out.println("lex: found int\n"); return (Parser.INT);
          }
        case 38: break;
        case 17: 
          { System.out.println("lex: found set\n"); return (Parser.SET);
          }
        case 39: break;
        case 11: 
          { System.out.println("lex: found ==\n"); return (Parser.EQUALEQUAL);
          }
        case 40: break;
        case 10: 
          { System.out.println("lex: found !=\n"); return (Parser.NOTEQUAL);
          }
        case 41: break;
        case 3: 
          { System.out.println("lex: found <\n"); return (Parser.LT);
          }
        case 42: break;
        case 1: 
          { System.out.println("lex: found individual char\n");
					yyparser.yylval = new ParserVal(yytext()); 
					return yycharat(0);		
					//return new ParserVal(yytext());
          }
        case 43: break;
        case 6: 
          { System.out.println("lex: found int_literal\n");
					yyparser.yylval = new ParserVal(Integer.parseInt(yytext())); 
					return (Parser.INTLITERAL);
          }
        case 44: break;
        case 12: 
          { System.out.println("lex: found <=\n"); return (Parser.LE);
          }
        case 45: break;
        case 25: 
          { System.out.println("lex: found bool_literal\n");
							yyparser.yylval = new ParserVal(yytext()); 
							return (Parser.BOOLLITERAL);
          }
        case 46: break;
        case 31: 
          { System.out.println("lex: found return\n"); return (Parser.RETURN);
          }
        case 47: break;
        case 23: 
          { System.out.println("lex: found else\n"); return (Parser.ELSE);
          }
        case 48: break;
        case 29: 
          { System.out.println("lex: found float\n"); return (Parser.FLOAT);
          }
        case 49: break;
        case 30: 
          { System.out.println("lex: found while\n"); return (Parser.WHILE);
          }
        case 50: break;
        case 27: 
          { System.out.println("lex: found void\n"); return (Parser.VOID);
          }
        case 51: break;
        case 19: 
          { System.out.println("lex: found not\n"); return (Parser.NOT);
          }
        case 52: break;
        case 2: 
          { System.out.println("lex: found id\n"); 
						yyparser.yylval = new ParserVal(yytext());
						return (Parser.ID);
          }
        case 53: break;
        case 9: 
          { System.out.println("lex: found or\n"); return (Parser.OR);
          }
        case 54: break;
        case 4: 
          { System.out.println("lex: found >\n"); return (Parser.GT);
          }
        case 55: break;
        case 8: 
          { System.out.println("lex: found if\n"); return (Parser.IF);
          }
        case 56: break;
        case 26: 
          { System.out.println("lex: found char\n"); return (Parser.CHAR);
          }
        case 57: break;
        case 14: 
          { System.out.println("lex: found >=\n"); return (Parser.GE);
          }
        case 58: break;
        case 34: 
          { System.out.println("lex: found question\n"); return (Parser.QUESTION);
          }
        case 59: break;
        case 33: 
          { System.out.println("lex: found boolean\n"); return (Parser.BOOLEAN);
          }
        case 60: break;
        case 32: 
          { /*Ignore*/
          }
        case 61: break;
        case 28: 
          // lookahead expression with fixed lookahead length
          yypushback(2);
          { /*Ignore*/
          }
        case 62: break;
        case 20: 
          // lookahead expression with fixed lookahead length
          yypushback(1);
          { /*Ignore*/
          }
        case 63: break;
        case 5: 
          { System.out.println("lex: found percent\n"); return (Parser.MOD);
          }
        case 64: break;
        case 13: 
          { System.out.println("lex: found <<\n"); return (Parser.INSERT);
          }
        case 65: break;
        case 7: 
          { System.out.println("lex: found whitespace or newline or tab\n");/* ignore */
          }
        case 66: break;
        case 22: 
          { System.out.println("lex: found char_literal\n");
					yyparser.yylval = new ParserVal(yycharat(1)); 
					return (Parser.CHARLITERAL);
          }
        case 67: break;
        case 15: 
          { System.out.println("lex: found string_literal\n"); 
					yyparser.yylval = new ParserVal(yytext().substring(1,yytext().length()-2));
					return (Parser.STRINGLITERAL);
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
